name: expense
version: '3.8'
networks:
  default:
    name: expense
volumes:
  mysql:    
services:
  mysql:
    image: mysql:D1
    container_name: mysql  #(its equal to --name mysql)
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume # -v volume-name:/path/in/container
  backend:
    image: backend:D1 
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: frontend:D1
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"