name: expense
networks:
  default:
    name: expense
services:
  mysql:
    image: mysql:D1
    container_name: mysql  #(its equal to --name mysql)
  backend:
    image: backend:D1 
    container_name: backend
    depends_on:
    - mysql
  frontend:
    image: frontend:D1
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"